version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    resource_class: large
    steps:
      - checkout
      - run: git lfs ls-files -l
      - run: git lfs ls-files -d
  push:
    parameters:
      macos:
        type: string
    macos:
      xcode: 14.3.1
    # available for Free plan
    resource_class: << parameters.macos >>
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run: |
          cat .gitattributes
      - run:
          name: create 500MB tar file
          command: head -c 524288000 /dev/urandom > sample500mb.tar
      - run: |
          ls -lah *.tar
      # - run: |
      #     git add sample500mb.tar
      # - run: |
      #     git config --global user.name "Kelvin Tay"
      #     git config --global user.email kelvintaywl@gmail.com
      # - run: |
      #     git commit -m '[skip ci] add sample50mb.tar'
      #     git checkout -b $CIRCLE_WORKFLOW_JOB_ID
      #     git push origin $CIRCLE_WORKFLOW_JOB_ID
      - when:
          condition:
            equal: [ "macos.m1.medium.gen1", << parameters.macos >> ]
          steps:
            - run: sudo softwareupdate --install-rosetta
      - aws-cli/setup
      - run:
         name: mock upload to GitHub LFS via S3 bucket in us-east-1
         command: |
           aws s3 cp sample500mb.tar "s3://kelvintaywl-mock-lfs/${CIRCLE_WORKFLOW_JOB_ID}/sample500mb.tar"

workflows:
  main:
    jobs:
      - push:
          matrix:
            parameters:
              macos:
                - macos.x86.medium.gen2
                - macos.m1.medium.gen1
