version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    resource_class: large
    steps:
      - checkout
      - run: git lfs ls-files -l
      - run: git lfs ls-files -d
  push:
    parameters:
      macos:
        type: string
    macos:
      xcode: 14.3.1
    # available for Free plan
    resource_class: << parameters.macos >>
    steps:
      - checkout
      - run: |
          cat .gitattributes
      - run:
          name: create 200MB tar file
          command: head -c 209715200 /dev/urandom > sample200mb.tar
      - run: |
          ls -lah *.tar
      - run: |
          git add sample200mb.tar
      - run: |
          git commit -m '[skip ci] add sample200mb.tar'
          git checkout -b $CIRCLE_WORKFLOW_JOB_ID
          git push origin $CIRCLE_WORKFLOW_JOB_ID

workflows:
  main:
    jobs:
      - push:
          matrix:
            parameters:
              macos:
                - macos.x86.medium.gen2
                - macos.m1.medium.gen1
